### ISSUE TITLE
Make FreeGeoIP.net optional

### ISSUE THREAD

**Issue by stefanw** [civio/medicamentalia#35]
You're using freegeoip.net which is automatically blocked by one of my browser extensions. The vaccines visualisations will not load as they depend on a successful call to freegeoip.net.

**Comment by rauldiazpoblete** [comment]
Fixed in https://github.com/civio/medicamentalia/commit/b37e8d75897794c9595d57124cacdd379b9ab5ee and deployed. Thanks @stefanw for the notice!
