### ISSUE TITLE
Make graphics work under https

### ISSUE THREAD

**Issue by stefanw** [civio/medicamentalia#36]
In order to embed graphics like [this one](http://medicamentalia.org/vaccines/measles-immunization/) it needs to be served completely over https.

So either medicamentalia.org will provide HTTPS or https://civio.github.io/medicamentalia/ can be used. Also all resources must be loaded over HTTPS (like freegeoip.net which currently is set to http). CSV files should be loaded relative to the current domain if the HTTPS endpoint of civio.github.io should be used.

**Comment by dcabo** [comment]
Hi, @stefanw. We're looking into enabling HTTPS support for the main site, we'll let you know asap.

**Comment by rauldiazpoblete** [comment]
Hi @stefanw. We have enabled HTTPS support (https://medicamentalia.org/) and also deployed german version of graphics (https://medicamentalia.org/vaccines/masern-immunisierung/).
Let us know if you need anything else.

**Comment by stefanw** [comment]
Awesome, thanks!
