### ISSUE TITLE
El gráfico de precios no se ve

### ISSUE THREAD

**Issue by dcabo** [civio/medicamentalia#39]
El gráfico de [esta página](http://medicamentalia.org/access/precios/) no se ve, ni en inglés ni en español. No hay errores de Javascript ni 404s al acceder a recursos, es como si el gráfico estuviera ahí pero fuera invisible o algo. Tras un vistazo rápido soy incapaz de ver qué pasa exactamente, así que te lo dejo para cuando vuelvas, @rauldiazpoblete.

**Comment by rauldiazpoblete** [comment]
Parece ser que el script de access.js estaba vacío por alguna razón que se me escapa. Ha bastado con renderizar los assets de nuevo para solucionarlo en https://github.com/civio/medicamentalia/commit/1fa12f2d89d4d4ea6cfff4807558e6149fe2ed7c
